run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - gofmt
    - revive
    - staticcheck
    - errcheck
    - ineffassign
    - gosimple
    - typecheck

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  revive:
    severity: warning
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: error-return
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
